//! `dif connect` — point an existing workspace at dif.sh Cloud.
//!
//! Writes the publishable key into `dif/config.yaml` and forces cloud events
//! mode, preserving comments and every other setting. Meant to be copy/pasted
//! straight from the cloud onboarding screen. It does not build — the generated
//! client is regenerated by `dif build`, which the success message points at.

use super::{validate_publishable_key, CmdError};
use clap::Args as ClapArgs;
use console::style;
use dif_core::config::EventsMode;
use dif_core::config_edit::upsert_events_block;
use dif_core::paths;
use dif_core::workspace::WorkspaceError;
use dif_core::Workspace;
use std::path::Path;
use std::process::ExitCode;

/// `dif connect` flags.
#[derive(ClapArgs, Debug)]
pub struct Args {
    /// Publishable key (dif_pk_…) from your dif.sh Cloud project. Written to
    /// dif/config.yaml and flowed into the generated client by `dif build`.
    #[arg(long)]
    pub key: String,

    /// Cloud base URL. Only needed for self-hosted deployments; defaults to
    /// https://cloud.dif.sh.
    #[arg(long)]
    pub url: Option<String>,
}

/// Entrypoint.
pub fn run(args: Args, json: bool) -> Result<ExitCode, CmdError> {
    let key = validate_publishable_key(&args.key)?;
    let cwd = std::env::current_dir()?;

    let workspace = match Workspace::load(&cwd) {
        Ok(ws) => ws,
        Err(WorkspaceError::NotFound(_)) => {
            report_no_workspace(json);
            return Ok(ExitCode::from(2));
        }
        Err(e) => return Err(e.into()),
    };

    let switched_from_custom = workspace.config.events().mode == EventsMode::Custom;
    let config_path = workspace.root.join(paths::CONFIG_FILE);
    let source = std::fs::read_to_string(&config_path)?;

    let updated = upsert_events_block(&source, EventsMode::Cloud, args.url.as_deref(), Some(&key))
        .map_err(|_| {
            CmdError::Other(
                "could not update dif/config.yaml automatically — edit the events: block by hand",
            )
        })?;
    std::fs::write(&config_path, updated)?;

    report_success(switched_from_custom, json);
    Ok(ExitCode::from(0))
}

fn report_no_workspace(json: bool) {
    if json {
        let payload = serde_json::json!({ "ok": false, "error": "no_workspace" });
        println!("{}", serde_json::to_string_pretty(&payload).unwrap());
        return;
    }
    eprintln!("{} no dif.sh workspace here.", style("✗").red().bold());
    eprintln!(
        "    run {} first (or {} to scaffold + connect in one step).",
        style("dif init").bold(),
        style("dif init --key <dif_pk_…>").bold(),
    );
}

fn report_success(switched_from_custom: bool, json: bool) {
    let config = Path::new(paths::CONFIG_FILE).display().to_string();
    if json {
        let payload = serde_json::json!({
            "ok": true,
            "config": config,
            "mode": "cloud",
            "switched_from_custom": switched_from_custom,
            "next": "dif build",
        });
        println!("{}", serde_json::to_string_pretty(&payload).unwrap());
        return;
    }
    let check = style("✓").green().bold();
    println!("{check} connected {config} to dif.sh Cloud");
    if switched_from_custom {
        println!(
            "{} switched events mode custom → cloud; your dif/events/{{exposure,track}}.ts are no longer used",
            style("⚠").yellow().bold(),
        );
    }
    println!(
        "  next: run {} to regenerate the client with your key",
        style("dif build").bold(),
    );
}
