// Cross-language bucketing anchor — the TS side of the contract.
//
// Loads `crates/dif-core/tests/fixtures/bucket_tests.json` (generated by
// the Rust side) and asserts the TS implementation produces byte-identical
// buckets for every entry. If this passes on both sides, the runtime
// contract holds.

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { BUCKET_NAMESPACE, bucket, saltFor, selectVariant } from "./bucket.js";

interface FixtureCase {
  experiment_id: string;
  user_id: string;
  bucket: number;
}

interface Fixture {
  version: number;
  namespace: string;
  cases: FixtureCase[];
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = resolve(
  __dirname,
  "../../..",
  "crates/dif-core/tests/fixtures/bucket_tests.json",
);
const EXPECTED_VERSION = 1;

function loadFixture(): Fixture {
  const raw = readFileSync(FIXTURE_PATH, "utf-8");
  return JSON.parse(raw) as Fixture;
}

describe("bucket cross-language fixture", () => {
  const fixture = loadFixture();

  it("fixture version matches", () => {
    assert.equal(
      fixture.version,
      EXPECTED_VERSION,
      `fixture v${fixture.version} but client expects v${EXPECTED_VERSION} — re-run Rust side with DIF_REGEN_FIXTURE=1 if intentional`,
    );
  });

  it("namespace matches BUCKET_NAMESPACE constant", () => {
    assert.equal(fixture.namespace, BUCKET_NAMESPACE);
  });

  it("every case in the fixture matches the TS bucket()", () => {
    for (const c of fixture.cases) {
      const salt = saltFor(c.experiment_id);
      const actual = bucket(salt, c.user_id);
      assert.equal(
        actual,
        c.bucket,
        `mismatch on (experiment=${c.experiment_id}, user=${c.user_id}): expected ${c.bucket}, got ${actual}`,
      );
    }
  });
});

describe("selectVariant", () => {
  it("picks the first variant whose cumulative weight crosses the bucket", () => {
    const variants = ["control", "variant_a"] as const;
    const weights = { control: 50, variant_a: 50 };
    // control owns [0, 5000), variant_a owns [5000, 10000).
    assert.equal(selectVariant(variants, weights, 0), "control");
    assert.equal(selectVariant(variants, weights, 4999), "control");
    assert.equal(selectVariant(variants, weights, 5000), "variant_a");
    assert.equal(selectVariant(variants, weights, 9999), "variant_a");
  });

  it("handles uneven weights", () => {
    const variants = ["control", "variant_a", "variant_b"] as const;
    const weights = { control: 70, variant_a: 20, variant_b: 10 };
    // [0, 7000), [7000, 9000), [9000, 10000)
    assert.equal(selectVariant(variants, weights, 0), "control");
    assert.equal(selectVariant(variants, weights, 6999), "control");
    assert.equal(selectVariant(variants, weights, 7000), "variant_a");
    assert.equal(selectVariant(variants, weights, 8999), "variant_a");
    assert.equal(selectVariant(variants, weights, 9000), "variant_b");
    assert.equal(selectVariant(variants, weights, 9999), "variant_b");
  });

  it("returns null when weights don't sum to 100", () => {
    const variants = ["control", "variant_a"] as const;
    const weights = { control: 30, variant_a: 30 };
    // Cumulative reaches 6000, bucket 9999 falls outside.
    assert.equal(selectVariant(variants, weights, 9999), null);
  });
});
