// Public types for @dif.sh/sdk.
// Kept in their own file so customer code can import them without dragging
// in the runtime.

/** A user-id resolver. Returns null when no user is identified. */
export type UserIdFn = () => string | null;

/** One audience attribute, scalar. */
export type AttrValue = string | number | boolean | null;

/** The bag of attributes the SDK consults when evaluating audience predicates. */
export type AttributeBag = Record<string, AttrValue>;

/** Audience predicate function — generated by `dif build`. */
export type AudienceFn = (attrs: Record<string, unknown>) => boolean;

/**
 * Legacy configuration shape accepted by `dif.configure(...)` (the alias kept
 * for backwards compatibility). New code should pass {@link DifInitConfig} to
 * `dif.init(...)` instead.
 *
 * @deprecated Use {@link DifInitConfig} via `dif.init()`.
 */
export interface DifConfig {
  /** How to look up the current user id at call time. */
  userId: UserIdFn;
  /** How to read audience attributes. Defaults to an empty bag. */
  attributes?: () => AttributeBag;
  /** One or more exposure sinks. */
  sink: Sink | Sink[];
  /** Global kill switch. Defaults to true. */
  enabled?: boolean;
}

/** Configuration passed to `dif.init(...)`. Superset of {@link DifConfig}. */
export interface DifInitConfig {
  /** Cloud project slug. Required when posting events to dif.sh Cloud. */
  project?: string;
  /** Browser-side write key (dif_pk_…). Safe to embed in bundles. */
  publishableKey?: string;
  /** Cloud base URL. Defaults to https://api.dif.sh. */
  apiUrl?: string;
  /** How to look up the current user id at call time. */
  userId?: UserIdFn;
  /** How to read audience attributes. Defaults to an empty bag. */
  attributes?: () => AttributeBag;
  /** One or more exposure sinks. */
  sink?: Sink | Sink[];
  /** Global kill switch. Defaults to true. */
  enabled?: boolean;
}

/** Anything that can receive an exposure event. */
export interface Sink {
  /** Sink identifier — for logs / dedupe. */
  readonly kind: string;
  /** Send one event. Must not throw — it should swallow + log internally. */
  emit(event: ExposureEvent): void;
}

/** Exposure event shape emitted to the configured sinks. */
export interface ExposureEvent {
  /** Always `"dif.exposure"`. */
  event: "dif.exposure";
  /** Experiment id. */
  experiment: string;
  /** Variant id chosen for this user. */
  variant: string;
  /** User id at the time of firing. */
  user_id: string;
  /** Surface the experiment runs on. */
  surface: string;
  /** Resolved bucket 0..9999. Surfaced for debugging. */
  bucket: number;
  /** Unix milliseconds. */
  fired_at: number;
  /** SDK version, e.g. `"@dif.sh/sdk@0.3.2"`. */
  source: string;
}

/** Optional properties on a `dif.track(metric, props)` call. */
export interface TrackProps {
  /** Numeric value carried by the metric (revenue cents, duration ms, etc.). */
  value?: number;
  /** ISO currency code (`USD`, `EUR`, …) — pairs with `value` for revenue. */
  currency?: string;
  /** Unit hint for non-currency values (e.g. `ms`, `count`). */
  unit?: string;
  /** Override the configured userId resolver for this call. */
  userId?: string;
  /** Override the event timestamp (defaults to now). */
  firedAt?: number;
  /** Caller-supplied idempotency key for safe retries. */
  idempotencyKey?: string;
  /** Override the SDK's "source" stamp. */
  source?: string;
  /** Arbitrary additional properties forwarded to the cloud as `props`. */
  props?: Record<string, unknown>;
}

/** Metric event shape sent to the cloud's `/v1/track` endpoint. */
export interface MetricEvent {
  metric: string;
  user_id: string;
  value?: number;
  currency?: string;
  unit?: string;
  fired_at: number;
  source: string;
  idempotency_key?: string;
  props?: Record<string, unknown>;
}

/**
 * The shape `dif build` emits into `.dif/generated/client.ts`. The generated
 * file calls {@link __register} once per active experiment with one of these.
 * Customers should never construct these by hand.
 */
export interface ExperimentSpec {
  /** Experiment id. Matches the `.md` filename stem. */
  id: string;
  /** Surface this experiment runs on. */
  surface: string;
  /** Variants in declared order. */
  variants: readonly string[];
  /** Hex salt computed by `dif-core` from the experiment id. */
  salt: string;
  /** Per-variant weight, 0..100. Sum is 100. */
  weights: Record<string, number>;
  /** Exclusion-group key, or null. */
  exclusionGroup: string | null;
  /** Compiled audience predicate. */
  audience: AudienceFn;
}
