// GENERATED by scripts/gen-version.mjs — do not edit.
// Kept in lockstep with package.json so emitted events stamp the right version.
export const VERSION = "0.4.0";
export const SOURCE = `@dif.sh/sdk@${VERSION}`;
