// Generates src/version.ts from package.json so the event `source` stamp always
// matches the published version — no hand-maintained version string to drift.
// Run by `npm run build` (and by scripts/prepare-release.sh after a version bump).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(here, "..", "package.json"), "utf8"));
const out = join(here, "..", "src", "version.ts");

writeFileSync(
  out,
  `// GENERATED by scripts/gen-version.mjs — do not edit.
// Kept in lockstep with package.json so emitted events stamp the right version.
export const VERSION = ${JSON.stringify(pkg.version)};
export const SOURCE = \`@dif.sh/sdk@\${VERSION}\`;
`,
);
console.log(`[dif] wrote src/version.ts (VERSION=${pkg.version})`);
