//! Codegen for `.dif/generated/client.ts`.
//!
//! Output is **deterministic**: same workspace input ⇒ byte-identical output.
//! No `prettier`, no `dprint` — we own the writer so the format is stable and
//! reviewable in PR diffs. The contract between Rust and TS is this one file
//! plus `.dif/context.json`; no FFI, no NAPI, no WASM at the runtime boundary.
//!
//! The file shape:
//! 1. Generated-by banner (with crate version — no timestamp, so PR diffs
//!    only churn on real changes).
//! 2. `import { __register } from "@dif.sh/sdk";`
//! 3. One `__register({...})` call per active experiment, sorted by id.
//!
//! Each `__register` call carries: id, surface, variants (as a `const` array
//! so V can be inferred as a string-literal union in the SDK), salt (hex),
//! weights, exclusion group, and an inlined audience predicate compiled from
//! the YAML.

use crate::{
    bucket,
    parse::ParsedExperiment,
    spec::{Audience, Experiment, Status, Variant},
    workspace::Workspace,
    VERSION,
};
use serde_yaml::Value;
use std::path::Path;

/// Emit the generated TypeScript client to `out_dir/client.ts`. Creates the
/// directory if it doesn't exist.
pub fn emit_client(workspace: &Workspace, out_dir: &Path) -> std::io::Result<()> {
    let source = render_client(workspace);
    std::fs::create_dir_all(out_dir)?;
    std::fs::write(out_dir.join("client.ts"), source)?;
    Ok(())
}

/// Render the full file contents as a string. Pulled out so tests can snapshot
/// the output without touching the filesystem.
pub fn render_client(workspace: &Workspace) -> String {
    let mut active: Vec<&ParsedExperiment> = workspace
        .active
        .iter()
        .filter(|p| matches!(p.spec.status, Status::Active))
        .collect();
    active.sort_by(|a, b| a.spec.id.cmp(&b.spec.id));

    let mut out = String::new();
    out.push_str(&banner());
    out.push_str("\nimport { __register } from \"@dif.sh/sdk\";\n\n");
    for parsed in &active {
        out.push_str(&render_experiment_export(&parsed.spec));
        out.push_str("\n\n");
    }
    out
}

/// Render one experiment as a `__register({...})` call. Pub for unit testing.
pub fn render_experiment_export(exp: &Experiment) -> String {
    let salt = hex_salt(&bucket::salt_for(&exp.id));
    let variants = render_variant_list(&exp.variants);
    let weights = render_weights(&exp.variants);
    let exclusion = render_optional_string(&exp.exclusion_group);
    let audience = render_audience(&exp.audience);

    let mut out = String::new();
    out.push_str("__register({\n");
    out.push_str(&format!("  id: \"{}\",\n", js_escape(&exp.id)));
    out.push_str(&format!("  surface: \"{}\",\n", js_escape(&exp.surface)));
    out.push_str(&format!("  variants: {variants} as const,\n"));
    out.push_str(&format!("  salt: \"{salt}\",\n"));
    out.push_str(&format!("  weights: {weights},\n"));
    out.push_str(&format!("  exclusionGroup: {exclusion},\n"));
    out.push_str(&format!("  audience: {audience},\n"));
    out.push_str("});");
    out
}

/// Convert a kebab-case experiment id into a camelCase TypeScript identifier.
/// Not currently used by the emitter (the runtime API is string-keyed) but
/// kept here for the future "typed named exports" feature mentioned in PLAN.
pub fn camel_case(kebab: &str) -> String {
    let mut out = String::with_capacity(kebab.len());
    let mut upper_next = false;
    for c in kebab.chars() {
        if c == '-' || c == '_' {
            upper_next = true;
        } else if upper_next {
            out.push(c.to_ascii_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

// -- helpers ------------------------------------------------------------------

fn banner() -> String {
    format!(
        "// generated by dif v{VERSION} — DO NOT EDIT.\n\
         //\n\
         // Regenerated by `dif build` on every run. Edits will be overwritten.\n\
         // Import this module once at app boot to populate the runtime registry\n\
         // that `dif(\"id\", branches)` consults at the call site.\n"
    )
}

fn render_variant_list(variants: &[Variant]) -> String {
    let items: Vec<String> = variants
        .iter()
        .map(|v| format!("\"{}\"", js_escape(&v.id)))
        .collect();
    format!("[{}]", items.join(", "))
}

fn render_weights(variants: &[Variant]) -> String {
    let items: Vec<String> = variants
        .iter()
        .map(|v| format!("\"{}\": {}", js_escape(&v.id), v.weight))
        .collect();
    format!("{{ {} }}", items.join(", "))
}

fn render_optional_string(opt: &Option<String>) -> String {
    match opt {
        Some(s) => format!("\"{}\"", js_escape(s)),
        None => "null".to_string(),
    }
}

/// Compile an audience to an arrow function. Empty audiences become
/// `() => true`; otherwise we emit one `if (...) return false;` per
/// constraint and `return true;` at the end.
fn render_audience(audience: &Audience) -> String {
    if audience.include.is_empty() && audience.exclude.is_empty() {
        return "() => true".to_string();
    }

    let mut body = String::new();
    body.push_str("(attrs) => {\n");
    for pred in &audience.include {
        for (key, value) in pred.0.iter() {
            let Some(name) = key.as_str() else { continue };
            match value {
                Value::Sequence(seq) => {
                    let items: Vec<String> = seq.iter().map(render_js_value).collect();
                    body.push_str(&format!(
                        "    if (![{}].includes(attrs[\"{}\"])) return false;\n",
                        items.join(", "),
                        js_escape(name)
                    ));
                }
                _ => {
                    body.push_str(&format!(
                        "    if (attrs[\"{}\"] !== {}) return false;\n",
                        js_escape(name),
                        render_js_value(value)
                    ));
                }
            }
        }
    }
    for pred in &audience.exclude {
        for (key, value) in pred.0.iter() {
            let Some(name) = key.as_str() else { continue };
            match value {
                Value::Sequence(seq) => {
                    let items: Vec<String> = seq.iter().map(render_js_value).collect();
                    body.push_str(&format!(
                        "    if ([{}].includes(attrs[\"{}\"])) return false;\n",
                        items.join(", "),
                        js_escape(name)
                    ));
                }
                _ => {
                    body.push_str(&format!(
                        "    if (attrs[\"{}\"] === {}) return false;\n",
                        js_escape(name),
                        render_js_value(value)
                    ));
                }
            }
        }
    }
    body.push_str("    return true;\n");
    body.push_str("  }");
    body
}

fn render_js_value(v: &Value) -> String {
    match v {
        Value::Null => "null".to_string(),
        Value::Bool(b) => {
            if *b {
                "true".into()
            } else {
                "false".into()
            }
        }
        Value::Number(n) => n.to_string(),
        Value::String(s) => format!("\"{}\"", js_escape(s)),
        Value::Sequence(seq) => {
            let items: Vec<String> = seq.iter().map(render_js_value).collect();
            format!("[{}]", items.join(", "))
        }
        // Mappings and tagged values shouldn't appear in audience predicate
        // *values* (only as the predicates themselves). Emit `null` so the
        // generated file still type-checks; validate.rs catches the real
        // problem.
        Value::Mapping(_) | Value::Tagged(_) => "null".to_string(),
    }
}

fn js_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out
}

fn hex_salt(salt: &[u8; 16]) -> String {
    let mut out = String::with_capacity(32);
    for b in salt {
        out.push_str(&format!("{b:02x}"));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::parse_experiment_str;

    fn parse(yaml_body: &str) -> Experiment {
        let source = format!("---\n{yaml_body}\n---\n");
        parse_experiment_str(&source).expect("parse").spec
    }

    const SIMPLE_EXP: &str = "id: checkout-cta-v2
status: active
owner: ada@acme.dev
surface: checkout
hypothesis: h
variants:
  - id: control
    weight: 50
  - id: variant_a
    weight: 50
metrics:
  primary: m
exclusion_group: checkout-copy
created: 2026-01-01";

    #[test]
    fn camel_case_handles_kebab() {
        assert_eq!(camel_case("checkout-cta-v2"), "checkoutCtaV2");
        assert_eq!(camel_case("simple"), "simple");
        assert_eq!(camel_case("multi-dash-name"), "multiDashName");
        assert_eq!(camel_case("snake_case"), "snakeCase");
    }

    #[test]
    fn hex_salt_is_32_chars() {
        let exp = parse(SIMPLE_EXP);
        let salt = bucket::salt_for(&exp.id);
        let hex = hex_salt(&salt);
        assert_eq!(hex.len(), 32);
        assert!(hex.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn empty_audience_is_constant_true() {
        let exp = parse(SIMPLE_EXP);
        let s = render_audience(&exp.audience);
        assert_eq!(s, "() => true");
    }

    #[test]
    fn include_scalar_renders_strict_equality() {
        let exp = parse(&format!(
            "{SIMPLE_EXP}\naudience:\n  include:\n    - country: US"
        ));
        let s = render_audience(&exp.audience);
        assert!(s.contains("attrs[\"country\"] !== \"US\""));
        assert!(s.contains("return true;"));
    }

    #[test]
    fn include_sequence_renders_includes_check() {
        let exp = parse(&format!(
            "{SIMPLE_EXP}\naudience:\n  include:\n    - country: [US, CA]"
        ));
        let s = render_audience(&exp.audience);
        assert!(s.contains("[\"US\", \"CA\"].includes(attrs[\"country\"])"));
    }

    #[test]
    fn exclude_renders_disqualification() {
        let exp = parse(&format!(
            "{SIMPLE_EXP}\naudience:\n  exclude:\n    - plan: free"
        ));
        let s = render_audience(&exp.audience);
        assert!(s.contains("attrs[\"plan\"] === \"free\""));
    }

    #[test]
    fn register_call_contains_required_fields() {
        let exp = parse(SIMPLE_EXP);
        let s = render_experiment_export(&exp);
        assert!(s.starts_with("__register({"));
        assert!(s.contains("id: \"checkout-cta-v2\""));
        assert!(s.contains("surface: \"checkout\""));
        assert!(s.contains("variants: [\"control\", \"variant_a\"] as const"));
        assert!(s.contains("salt: \""));
        assert!(s.contains("weights: { \"control\": 50, \"variant_a\": 50 }"));
        assert!(s.contains("exclusionGroup: \"checkout-copy\""));
        assert!(s.contains("audience:"));
        assert!(s.ends_with("});"));
    }

    #[test]
    fn deterministic_output() {
        let exp = parse(SIMPLE_EXP);
        let a = render_experiment_export(&exp);
        let b = render_experiment_export(&exp);
        assert_eq!(a, b, "codegen must be deterministic");
    }

    #[test]
    fn js_escape_handles_specials() {
        assert_eq!(js_escape("plain"), "plain");
        assert_eq!(js_escape("with \"quote\""), "with \\\"quote\\\"");
        assert_eq!(js_escape("back\\slash"), "back\\\\slash");
        assert_eq!(js_escape("line\nbreak"), "line\\nbreak");
    }
}
