#!/usr/bin/env node
// Mirrors the Claude Code skills that `dif init` embeds (the source of truth,
// under cli/crates/dif-cli/assets/claude/skills/) into the top-level skills/
// directory, where `npx skills add dif-sh/dif` discovers them.
//
// skills/dif-docs/ is authored directly in skills/ (no crate copy) and is left
// alone. Its twin on the website, static/.well-known/agent-skills/dif-docs/
// SKILL.md in the dif-site repo, is kept in sync by hand.
//
// It also mirrors the Cursor rule that `dif init` writes to
// .cursor/rules/dif.mdc into the top-level rules/dif.mdc, where
// cursor.directory detects it (rules/*.mdc). The repo copy is the same
// frontmatter and body without the "generated by dif vX" stamp line, so it
// does not change on a version bump. The Rust test
// `repo_cursor_rule_matches_template` in cli/crates/dif-cli/src/cmd/init.rs
// pins the same file against the compiled template.
//
// Usage:
//   node scripts/sync-skills.mjs          copy assets → skills/ and rules/
//   node scripts/sync-skills.mjs --check  exit 1 if either has drifted (CI)

import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "cli", "crates", "dif-cli", "assets", "claude", "skills");
const target = join(root, "skills");
const check = process.argv.includes("--check");

function listFiles(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? listFiles(path) : [path];
  });
}

const skills = readdirSync(source).filter((name) => statSync(join(source, name)).isDirectory());
const drift = [];

for (const skill of skills) {
  const from = join(source, skill);
  const to = join(target, skill);
  const expected = listFiles(from).map((p) => relative(from, p)).sort();
  const actual = listFiles(to).map((p) => relative(to, p)).sort();

  for (const rel of new Set([...expected, ...actual])) {
    const a = join(from, rel);
    const b = join(to, rel);
    if (!existsSync(a)) drift.push(`skills/${skill}/${rel} (not in assets)`);
    else if (!existsSync(b)) drift.push(`skills/${skill}/${rel} (missing)`);
    else if (!readFileSync(a).equals(readFileSync(b))) drift.push(`skills/${skill}/${rel} (differs)`);
  }

  if (!check) {
    rmSync(to, { recursive: true, force: true });
    cpSync(from, to, { recursive: true });
  }
}

// --- rules/dif.mdc (the Cursor rule) ----------------------------------------
// Rebuilt from the same two inputs `cursor_mdc()` uses in init.rs: the
// CURSOR_RULE_DESCRIPTION constant and assets/cursorrules.txt.
const initRs = readFileSync(join(root, "cli", "crates", "dif-cli", "src", "cmd", "init.rs"), "utf8");
const descMatch = initRs.match(/const CURSOR_RULE_DESCRIPTION: &str = "([^"\\]+)";/);
if (!descMatch) {
  console.error("cli/crates/dif-cli/src/cmd/init.rs: CURSOR_RULE_DESCRIPTION not found");
  process.exit(1);
}
const ruleBody = readFileSync(join(root, "cli", "crates", "dif-cli", "assets", "cursorrules.txt"), "utf8");
const expectedRule = `---\ndescription: ${descMatch[1]}\nglobs: dif/**\nalwaysApply: false\n---\n\n${ruleBody}`;
const rulePath = join(root, "rules", "dif.mdc");
const ruleDrift = !existsSync(rulePath)
  ? "rules/dif.mdc (missing)"
  : readFileSync(rulePath, "utf8") !== expectedRule
    ? "rules/dif.mdc (differs)"
    : null;

if (!check) {
  mkdirSync(dirname(rulePath), { recursive: true });
  writeFileSync(rulePath, expectedRule);
}

if (check) {
  if (drift.length > 0) {
    console.error("skills/ is out of sync with cli/crates/dif-cli/assets/claude/skills/:");
    for (const line of drift) console.error(`  ${line}`);
  }
  if (ruleDrift) {
    console.error("rules/ is out of sync with cli/crates/dif-cli/assets/cursorrules.txt:");
    console.error(`  ${ruleDrift}`);
  }
  if (drift.length > 0 || ruleDrift) {
    console.error("run: node scripts/sync-skills.mjs");
    process.exit(1);
  }
  console.log(`skills/ in sync (${skills.length} skills mirrored from assets)`);
  console.log("rules/dif.mdc in sync with the dif init Cursor rule");
} else {
  console.log(`mirrored ${skills.length} skills into skills/`);
  console.log("wrote rules/dif.mdc");
}
